#!/usr/bin/env bash
set -e
rm -rf ./dist
yarn run build:prod

rsync \
  --recursive \
  --verbose \
  --archive \
  --update \
  --delete \
  --prune-empty-dirs \
  --compress \
  ./dist/* \
  pixelastic:/var/www/talks.pixelastic.com/slides/algolia-community-reddinx/

